const base = 'TERRITORIES'

export const ADD_SQUARE_POSITIONS_TO_CURRENT = `${base}/ADD_SQUARE_POSITIONS_TO_CURRENT`
export const ADD_SQUARE_POSITIONS_TO_OTHER = `${base}/ADD_SQUARE_POSITIONS_TO_OTHER`
export const APPEND_TERRITORY = `${base}/APPEND_TERRITORY`
export const FETCH_CURRENT = `${base}/FETCH_CURRENT`
export const FETCH_OTHERS = `${base}/FETCH_OTHERS`
export const REMOVE_SQUARE_POSITIONS_FROM_CURRENT = `${base}/REMOVE_SQUARE_POSITIONS_FROM_CURRENT`
export const REMOVE_SQUARE_POSITIONS_FROM_OTHER = `${base}/REMOVE_SQUARE_POSITIONS_FROM_OTHER`
export const SET_CURRENT = `${base}/SET_CURRENT`
export const SET_OTHERS = `${base}/SET_OTHERS`
export const UPDATE_CURRENT = `${base}/UPDATE_CURRENT`
export const UPDATE_OTHER_BY_USER_ID = `${base}/UPDATE_OTHER_BY_USER_ID`
