export const CORE_GAMEPLAY_ACCEPTANCE = 'coreGameplayAcceptance'
export const GAME_SESSION_STARTED = 'gameSessionStarted'
export const SQUARE_CAPTURED = 'squareCaptured'
export const SECOND_TURN_MADE = 'secondTurnMade'
export const THIRD_TURN_MADE = 'thirdTurnMade'
export const FIFTH_TURN_MADE = 'fifthTurnMade'
export const EIGHTH_TURN_MADE = 'eighthTurnMade'
export const CLICKED_BECOME_PATREON = 'clickedBecomePatreon'
